### ISSUE TITLE
Incompatible with Streamlit 1.30.0

### ISSUE THREAD

**Issue by vporoshin** [stonier/streamlit_parameters#6]

**Comment by msabramo** [comment]
Are you referrring to this warning or something else?

![Screenshot 2024-03-26 at 3 54 21 PM](https://github.com/stonier/streamlit_parameters/assets/305268/0bc8ad42-ad54-4b08-b3b0-042c11cc96af)

**Comment by stonier** [comment]
Upgrade released in v0.2.0
